@startuml
left header

        <font color=000 size=18><b>ID:</b> UC6
        <font color=000 size=18><b>Назва:</b> Аналіз власного тексту
        <font color=000 size=18><b>Учасники:</b> Користувач, система
        <font color=000 size=18><b>Передумови:</b> Зареєстрований користувач
        <font color=000 size=18><b>Результат:</b> Користвувач отримав аналіз власного тексту
        <font color=000 size=18><b>Виключні ситуації:</b>
        <font color=000 size=18> EX4.1 Не правильно відправлений запит
        <font color=000 size=18> EX4.2 Немає доступу до сервісу

        <font color=000 size=18><b>Основний сценарій:</b>
    end header

    |Користувач|
        start
        
        : Натискає на кнопку аналізу тексту;
        
    |Система|
        
        : Видає відповідну форму;

    |Користувач|
    
        : Заповнює форму (вводить текст, що йому треба проаналізувати);
        : Відправляє заповнену форму;
        
    |Система|
    
        : Обробляє дані в формі;
         note right #ffaaaa
        <b> Можлива
        <b> EX4.1
        end note
        
        : Аналізує відповідний текст та видає результат на окремій сторінці;
        note right #ffaaaa
        <b> Можлива
        <b> EX4.2
        end note
        
        stop;
    
right footer
AMC
НТУУ КПІ ім. І.Сікорського
Киів - 2020
end footer
@enduml
