@startuml
    left header

        <font color=000 size=18><b>ID:</b> UC4
        <font color=000 size=18><b>Назва:</b> Створення проєкту
        <font color=000 size=18><b>Учасники:</b> Користувач, система, GitHub
        <font color=000 size=18><b>Передумови:</b> Користувач авторизований в системі
        <font color=000 size=18><b>Результат:</b> Користвувач створив новий проєкт
        <font color=000 size=18><b>Виключні ситуації:</b>
        <font color=000 size=18> EX4.1 Не правильно заповнена форма
        <font color=000 size=18> EX4.2 Немає доступу до бази даних
        <font color=000 size=18> EX4.3 GitHub не доступний

        <font color=000 size=18><b>Основний сценарій:</b>
    end header

    |Користувач|
        start
        
        : Натискає на кнопку створення проєкту;
        
    |Система|
        
        : Надсилає форму для заповнення;

    |Користувач|
    
        : Заповнює форму основною
        інформацією про новий проєкт;
        : Відправляє заповнену форму;
        
    |Система|
    
        : Обробляє дані в формі;
         note right #ffaaaa
        <b> Можлива
        <b> EX4.1
        end note
        
        : Створює проєкт з основними 
        властивостями в базі даних;
        note right #ffaaaa
        <b> Можлива
        <b> EX4.2
        end note
        
        : Відправляє форму для інтеграції з GitHub;
    
    |Користувач|
        
        : Натискає на кнопку для інтеграції з GitHub;

    |Система|
        
        : Підключає існуючий репозиторій з GitHub;
        note right #ffaaaa
        <b> Можлива
        <b> EX4.3
        end note
        
    |GitHub|
    
        : Обробляє запит на підключення репозиторію;
        : Повертає повідомлення про успішне підключення;
        
    |Система|
        
        : Повертає створений проєкт, готовий до роботи;
    
    |Користувач|
        
        : Отримує повідомлення про успішне створення проєкту;
        
        stop;
    
right footer
ProjectsLab
НТУУ КПІ ім. І.Сікорського
Киів - 2020
end footer

@enduml