@startuml

    |Користувач|
        start
        
        : Надсилає запит на створення нової задачі;
        
    |Система|
        
        : Оброблює запит на створення;
        : Надсилає форму для заповнення;
        
    |Користувач|
    
        : Заповнює форму:
        - назва нової задачі
        - приорітет задачі
        - порядок виконання задачі
        - хто виконує задачу
        - дедлайн виконання задачі;
        
    |Система|
    
        : Оброблює форму на створення
        - усі поля заповнені
        - назва унікальна
        - порядок виконання не конфліктує з порядком інших задач
        - назначений розробник допущений до цього проекту;
        note right #ffaaaa
        <b> Можливо
        <b> EX8.1, EX8.2, 
        <b> EX8.3
        end note
    
        : Створює нову задачу;
        
        
    |Користувач|
        : Отримує повідомлення про створення задачі;
        stop;

@enduml
