@startuml
    left header

        <font color=000 size=18><b>ID:</b> UC8
        <font color=000 size=18><b>Назва:</b> Створення задачі
        <font color=000 size=18><b>Учасники:</b> Користувач, система
        <font color=000 size=18><b>Передумови:</b> Користувач має права тімліда
        <font color=000 size=18><b>Результат:</b> Створення задачі
        <font color=000 size=18><b>Виключні ситуації:</b>
        <font color=000 size=18> EX8.1 дані введені некоректно
        <font color=000 size=18> EX8.2 таке завдання вже існує
        
        <font color=000 size=18><b>Основний сценарій:</b>
    end header

    |Користувач|
        start
        
        : Надсилає запит на створення задачі;
        
    |Система|
        
        : Оброблює запит на створення;
        : Надсилає форму для заповнення;
        
    |Користувач|
    
        : Заповнює та надсилає форму;
        note right #ffaaaa
        <b> Можливо
        <b> EX8.1
        end note
        
    |Система|
    
        : Оброблює форму на створення;
    
        : Надсилає запит на створення завдання до загальної бази даних;
        
    |Користувач|
        : Отримує повідомлення про створення задачі;
        note right #ffaaaa
        <b> Можливо
        <b> EX8.2
        end note
        stop;

@enduml