@startuml

    |Користувач|
        start
        
        : Натискає кнопку "Редагувати задачу";
        
    |Система|
        
        : Оброблює запит на редагування;
        note right #ffaaaa
        <b> Можливо
        <b> EX10.1
        end note
        : Надсилає форму з даними про задачу;
        
    |Користувач|
    
        : Змінює форму з данимим (не обов'язково кожне поле):
        - нова назва
        - новий дедлайн
        - новий порядок виконання
        - новий виконавець завдання
        - новий дедлайн завдання;
    
    |Система|
        : Оброблює форму на зміну завдання:
        - нова назва унікальна
        - новий порядок виконання не конфліктує з порядком інших задач
        - новий назначений розробник допущений до цього проекту;
        note right #ffaaaa
        <b> Можливо
        <b> EX10.2
        end note
        
    |Користувач|
        : Отримує повідомлення про зміну задачі;
        stop;

@enduml
