@startuml
    left header

        <font color=000 size=18><b>ID:</b> UC10
        <font color=000 size=18><b>Назва:</b> Редагування задачі
        <font color=000 size=18><b>Учасники:</b> Користувач, система
        <font color=000 size=18><b>Передумови:</b> Користувач має права тімліда
        <font color=000 size=18><b>Результат:</b> Користувач редагує задачу
        <font color=000 size=18><b>Виключні ситуації:</b>
        <font color=000 size=18>EX10.1 такого завдання не існує
        <font color=000 size=18>EX10.2 некоректно введені дані
        
        <font color=000 size=18><b>Основний сценарій:</b>
    end header

    |Користувач|
        start
        
        : Надсилає запит на редагування задачі;
        
    |Система|
        
        : Оброблює запит на редагування;
        : Надсилає запит до загальної бази для отримання даних;
        note right #ffaaaa
        <b> Можливо
        <b> EX10.1
        end note
        : Надсилає форму з даними про задачу;
        
    |Користувач|
    
        : Вводить нові дані;
        note right #ffaaaa
        <b> Можливо
        <b> EX10.2
        end note
        : Надсилає форму;
    
    |Система|
        : Надсилає запит на зміну бази даних;
        stop;

@enduml