@startuml
left header

        <font color=000 size=18><b>ID:</b> UC4
        <font color=000 size=18><b>Назва:</b> Авторизація користувача
        <font color=000 size=18><b>Учасники:</b> Користувач, система.
        <font color=000 size=18><b>Передумови:</b> Користувач авторизований в системі
        <font color=000 size=18><b>Результат:</b> Користувач переглядає свою історію 
        <font color=000 size=18><b>Виключні ситуації:</b>
        <font color=000 size=18> EX6.1 Немає доступу до історій пошуку


        <font color=000 size=18><b>Основний сценарій:</b>
    end header

    |Користувач|
        start
        
        : Натискає на кнопку історій пошуку;
        
    |Система|
        
        : Переносить на сторінку історій пошуку;
         note right #ffaaaa
        <b> Можлива
        <b> EX6.1
        end note

    |Користувач|
    
        : Отримує доступ до історій пошуку;
        stop;
    
right footer
AMC
НТУУ КПІ ім. І.Сікорського
Киів - 2020
end footer
@enduml
