@startuml
left header

        <font color=000 size=18><b>ID:</b> UC3
        <font color=000 size=18><b>Назва:</b> Інформація щодо проекту та команди
        <font color=000 size=18><b>Учасники:</b> Користувач, система
        <font color=000 size=18><b>Передумови:</b> Незареєстрований/зареєстрований користувач
        <font color=000 size=18><b>Результат:</b> Користвувач отримав інформацію щодо проекту
        <font color=000 size=18><b>Виключні ситуації:</b>

        <font color=000 size=18><b>Основний сценарій:</b>
    end header

    |Користувач|
        start
        
        : Натискає на кнопку подивитися інформацію щодо проекту;
        
    |Система|
        
        : Переходить на окрему сторінку;
        : Видає інформацію щодо команди розробників
        : Видає документацію по проекту
        
     ;
   
right footer
AMC
НТУУ КПІ ім. І.Сікорського
Киів - 2020
end footer
@enduml
