@startuml
    left header

        <font color=000 size=18><b>ID:</b> UC2
        <font color=000 size=18><b>Назва:</b> Авторизація користувача
        <font color=000 size=18><b>Учасники:</b> Гість, система
        <font color=000 size=18><b>Передумови:</b> Створений акаунт користувача
        <font color=000 size=18><b>Результат:</b> Користувач авторизований в системі
        <font color=000 size=18><b>Виключні ситуації:</b>
        <font color=000 size=18> EX2.1 Не заповнені поля для вводу
        <font color=000 size=18> EX2.2 Не вірно введене ім'я користувача або (та) пароль
        <font color=000 size=18> EX2.3 Акаунт користувача не активований
        
        <font color=000 size=18><b>Основний сценарій:</b>
    end header

    |Гість|
        start
        
        : Натискає на посилання для входу;
        : Заповнює поля форми;
        
    |Система|
        
        : Обробка полів з даними;
        
        note right #ffaaaa
        <b> Можлива
        <b> EX2.1
        end note
        
        : Пошук існуючого запису
        користувача в базі даних;
        note right #ffaaaa
        <b> Можливі
        <b> EX2.2, EX2.3
        end note
        
        : Повернення зашифрованого ключа
        для авторизації користувача;
        
    |Гість|
    
        : Успішний вхід в систему;
        
        stop;
    
right footer

ProjectsLab
НТУУ КПІ ім. І.Сікорського
Киів - 2020
end footer

@enduml