@startuml

    |Користувач|
        start
        
        : Надсилає запит на перегляд списку задач проекту;
        
    |Система|
        
        : Оброблює запит на перегляд;
        : Отримує писок задач згідно проекту;
        : Надсилає список отриманих задач;
        
    |Користувач|
    
        : Отримує список задач проекту;
        stop;

@enduml
