@startuml
    left header

        <font color=000 size=18><b>ID:</b> UC9
        <font color=000 size=18><b>Назва:</b> Перегляд задач проекту
        <font color=000 size=18><b>Учасники:</b> Користувач, система
        <font color=000 size=18><b>Передумови:</b> Користувач має права доступу до проекту
        <font color=000 size=18><b>Результат:</b> Користувач отримує список задач
        
        <font color=000 size=18><b>Основний сценарій:</b>
    end header

    |Користувач|
        start
        
        : Надсилає запит на перегляд задач проекту;
        
    |Система|
        
        : Оброблює запит на перегляд;
        : Надсилає запит на перегляд задач проекту до загальної бази даних;
        
    |Користувач|
    
        : Отримує список задач проекту;
        stop;

@enduml