@startuml
left header

        <font color=000 size=18><b>ID:</b> UC5
        <font color=000 size=18><b>Назва:</b> Налаштування
        <font color=000 size=18><b>Учасники:</b> Користувач, система
        <font color=000 size=18><b>Передумови:</b> Зареєстрований користувач
        <font color=000 size=18><b>Результат:</b> Змінив власні налаштування
        <font color=000 size=18><b>Виключні ситуації:</b>
        <font color=000 size=18> EX4.1 Не правильно відправлений запит
        <font color=000 size=18> EX4.2 Немає доступу до сервісу

        <font color=000 size=18><b>Основний сценарій:</b>
    end header

    |Користувач|
        start
        
        : Натискає на кнопку налаштувань;
        
    |Система|
        
        : Переносить на сторінку налаштувань;

    |Користувач|
    
        : Отримує доступ до зміни логіну і паролю,
         зможе персоналізувати зовнішній вигляд сторінок
         (змніна шруфту, теми);
        : Вносить зміни;
        : Натискає на кнопку збереження;

           

    |Система|
    
        : Обробляє внесені зміни;
         note right #ffaaaa
        <b> Можлива
        <b> EX4.1
        end note
        
        : Зберігає внесені зміни;
        note right #ffaaaa
        <b> Можлива
        <b> EX4.2
        end note
        
        stop;
    
right footer
AMC
НТУУ КПІ ім. І.Сікорського
Киів - 2020
end footer
@enduml
