@startuml
Actor User
participant github
participant plantuml.com
User -> github: View "file_with_uml".md
github --> User: Rendered HTML with <img> tag 
User -> plantuml.com: Request plantuml proxy
plantuml.com -> github: Get puml source
github --> plantuml.com : Return puml source
plantuml.com -> plantuml.com: Render diagram
plantuml.com --> User: Return png view of diagram 
@enduml