@startuml
entity Dataverse #53CC47
entity Dataverse.id #B7FBB1

entity Dataset #53CC47
entity Dataset.id #B7FBB1

entity File #8DE485
entity File.id #B7FBB1
entity File.content #B7FBB1

entity MetadataGroup #8DE485
entity MetadataGroup.id #B7FBB1
entity MetadataGroup.key #B7FBB1
entity MetadataGroup.value #B7FBB1

entity Metadata #8DE485
entity Metadata.id #B7FBB1
entity Metadata.key #B7FBB1
entity Metadata.value #B7FBB1

entity Admin #7BE7B8
entity Author #7BE7B8

entity User #7BE7B8
entity User.id #C0FCE2
entity User.nickname #C0FCE2
entity User.email #C0FCE2
entity User.password #C0FCE2

entity Acess #7BE7B8
entity Acess.role #C0FCE2

Dataverse <-- Dataverse.id
Dataverse "1,*"<--"0,*" Admin
Dataverse "1,1"<--"1,*" Author
Dataverse "1,1"--"0,*" Dataset


MetadataGroup <-- MetadataGroup.id
MetadataGroup <-- MetadataGroup.key
MetadataGroup <-- MetadataGroup.value

MetadataGroup "0,*"-l->"0,1" File
MetadataGroup "0,*"-r->"0,1" Dataverse
MetadataGroup "0,*"-->"0,1" Dataset
MetadataGroup "1,1"--"0,*" Metadata

Metadata <-- Metadata.id
Metadata <-- Metadata.key
Metadata <-- Metadata.value

File <-- File.id
File <-- File.content

Dataset <-- Dataset.id
Dataset "1,1"--"0,*" File

Author "0,*"--|>"1,*" Acess
Admin "0,*"--|>"1,1" Acess
User <|-l- Acess
Acess <-- Acess.role
User <-- User.id
User <-- User.nickname
User <-- User.email
User <-- User.password
@enduml
