@startuml
entity Dataverse #53CC47 {
    id: INT
}
  
entity Dataset #53CC47 {
    id: INT
}

entity Feature #8DE485 {
    id: INT
    description: TEXT
}
entity Entity #8DE485 {
    id: INT
}
entity Metadata #8DE485 {
    id: INT
    key
    metadata:TEXT
}
entity Datapoint #8DE485 {
    id: INT
    content: TEXT
}
  
  
Dataverse "1,1"-- "0,*" Dataset
Dataset "1,1"--"0,*" Feature
Dataset "1,1"--"0,*" Entity
Dataset "1,1"--"0,*" Metadata
Dataset "1,1"--"0,*" Datapoint
@enduml
