@startuml
left header
        
        <font color=000 size=16><b>ID:</b> UC_1.4.1
        <font color=000 size=16><b>Назва:</b> Переглянути набір даних
        <font color=000 size=16><b>Учасники:</b> Користувач, Система
        <font color=000 size=16><b>Передумови:</b> Користувач знайшов набір даних
        <font color=000 size=16><b>Результат:</b> Потрібний набір даних переглянутий
        <font color=000 size=16><b>Виключні ситуації:</b> Відсутні
        
        <font color=000 size=16><b>Основний сценарій:</b>
        
    end header

    |Користувач|
        start
        : Натискає на поле "Перегляд";
    |Система|
        : Виводить набір файлів;
    |Користувач|
        stop;
@enduml
