@startuml
left header
        
        <font color=000 size=16><b>ID:</b> UC_1.3
        <font color=000 size=16><b>Назва:</b> Знайти набір даних
        <font color=000 size=16><b>Учасники:</b> Користувач, Система
        <font color=000 size=16><b>Передумови:</b> Користувач відкрив розділ "Каталог"
        <font color=000 size=16><b>Результат:</b> Потрібний набір даних знайдений
        <font color=000 size=16><b>Виключні ситуації:</b>
        <font color=000 size=16> ЕХ.1.3.1 Шуканий набір даних відсутній
        
        <font color=000 size=16><b>Основний сценарій:</b>
        
    end header

    |Користувач|
        start
        : Вводить запит в поле пошуку;
        : Натискає на кнопку "Пошук";
    |Система|
        : Виводить шуканий звіт;
        note right #ffaaaa
        <b> Можливо
        <b> EX.1.3.1
        end note
    |Користувач|
        stop;
@enduml
