@startuml
left header
        
        <font color=000 size=16><b>ID:</b> UC_1.1
        <font color=000 size=16><b>Назва:</b> Створити обліковий запис
        <font color=000 size=16><b>Учасники:</b> Користувач, Система
        <font color=000 size=16><b>Передумови:</b> Відсутні
        <font color=000 size=16><b>Результат:</b> Створено новий обліковий запис
        <font color=000 size=16><b>Виключні ситуації:</b>
        <font color=000 size=16> EX_1.1 Гість перервав процес реєстрації
        <font color=000 size=16> EX_1.2 Гість увів некоректні дані
        <font color=000 size=16> EX_1.3 Гість не підтвердив електрону адресу
        
        <font color=000 size=16><b>Основний сценарій:</b>
        
    end header

    |Користувач|
        start
        : Натискає кнопку [Реєстрація];
    |Система|
        :           Пропонує форму 
        "Реєстрація нового користувача";
    |Користувач|    
        : Заповнює поля з
        особистими даними;
        note right #ffaaaa
        <b> Можливо
        <b> EX_1.1
        end note
        
        : Підтверджує обізнанність
        правилами користування;
    |Система|
        : Перевіряє введені дані;
        note right #ffaaaa
        <b> Можливо
        <b> EX_1.1.2
        end note

        : Надсилає листа для 
        підтвердження реєстрації;
    |Користувач|
        : За посиланням підтверджує
                 обліковий запис;
        note right #ffaaaa
        <b> Можливо
        <b> EX_1.3
        end note

        stop;
@enduml
