@startuml
left header
        
        <font color=000 size=16><b>ID:</b> UC_1.4.2
        <font color=000 size=16><b>Назва:</b> Завантажити набір даних
        <font color=000 size=16><b>Учасники:</b> Користувач, Система
        <font color=000 size=16><b>Передумови:</b> Користувач завантажив набір даних
        <font color=000 size=16><b>Результат:</b> Потрібний набір даних завантажений
        <font color=000 size=16><b>Виключні ситуації:</b> Відсутні
        
        <font color=000 size=16><b>Основний сценарій:</b>
        
    end header

    |Користувач|
        start
        : Обирає файли необхідні\nдля завантаження або весь\nнабір даних;
        : Натискає на кнопку "Завантажити";
    |Система|
        : Завантажує набір файлів;
    |Користувач|
        stop;
@enduml
