@startuml
left header
        
        <font color=000 size=16><b>ID:</b> UC_2.2.2
        <font color=000 size=16><b>Назва:</b> Внести зміни до набору данних
        <font color=000 size=16><b>Учасники:</b> Автор, Система
        <font color=000 size=16><b>Передумови:</b> Відсутні
        <font color=000 size=16><b>Результат:</b> Редагований набір данних
        <font color=000 size=16><b>Виключні ситуації:</b>
        <font color=000 size=16> EX_2.2.2.1 Автор перервав процес редагування
        <font color=000 size=16> EX_2.2.2.2 Автор вніс некоректні зміни
        
        <font color=000 size=16><b>Основний сценарій:</b>
        
    end header

    |Автор|
        start
        : Натискає кнопку [Редагувати];
    |Система|
        : Пропонує форму 
                        "Редагування" 
            "відредагуйте ім'я, приналежність,
            ідентифікатор, категорію, 
            контактну електронну адресу,
            опис, поля метаданих";
    |Автор|    
        : Вносить зміни;
        note right #ffaaaa
        <b> Можливо
        <b> EX_2.2.2.1
        end note
        
        : Відправляє зміни;
    |Система|
        : Перевіряє введені дані;
        note right #ffaaaa
        <b> Можливо
        <b> EX_2.2.2.2
        end note

        : Публікує відредагований
                         звіт;
    |Автор|    
        stop;
@enduml
