@startuml
left header
        
        <font color=000 size=16><b>ID:</b> UC_2.1
        <font color=000 size=16><b>Назва:</b> Створити набір данних
        <font color=000 size=16><b>Учасники:</b> Автор, Система
        <font color=000 size=16><b>Передумови:</b> Немає
        <font color=000 size=16><b>Результат:</b> Створення нової статті та публікація на ресурсі
        <font color=000 size=16><b>Виключні ситуації:</b>
        <font color=000 size=16> EX_2.1.1 Наявна ідентична стаття на ресурсі
        
        <font color=000 size=16><b>Основний сценарій:</b>
        
    end header

    |Автор|
        start
        : Натискає кнопку [Додати статтю...];
    |Система|
        : Пропонує форму 
           "Створення нової статті"
           "Заповнити поля:"
           "Host Dataverse, Ім'я супроводу даних,
            Приналежність, Ідентифікатор, Примітка,
            Категорія, Електронна адреса, Опис.";
    |Автор|    
        : Заповнює поля;
    |Система|
        : Проводить пошук ідентичної статті у базі;
        note right #ffaaaa
        <b> Можливо
        <b> EX_2.1.1
        end note
        : Надає для заповнення поля: тіло
документу, посилання на джерела;
    |Автор|
        : Корегує інформацію за допомогою інструментарію
та натискає кнопку [Завершити створення];
    |Система|
        : Перевіряє коректність введених даних та
надсилає запит Адміністратору;
    |Автор|
        stop;
@enduml
