@startuml
left header
        
        <font color=000 size=16><b>ID:</b> UC_3.2
        <font color=000 size=16><b>Назва:</b> Моніторинг
        <font color=000 size=16><b>Учасники:</b> Адміністратор, Система
        <font color=000 size=16><b>Передумови:</b> Відсутні
        <font color=000 size=16><b>Результат:</b> Система виводить статистику по сервісу
        <font color=000 size=16><b>Виключні ситуації:</b> Відсутні
        
        <font color=000 size=16><b>Основний сценарій:</b>
        
    end header

    |Розробник|
        start
        : Обирає один з пунктів\n(Munin, HTTP трафік, AWStats)\nз панелі адміністратора;
    |Система|
        : Система виводить статистику по сервісу;
    |Розробник|
        stop;
@enduml
