@startuml
left header
        
        <font color=000 size=16><b>ID:</b> UC_3.1
        <font color=000 size=16><b>Назва:</b> Редагувати звіт
        <font color=000 size=16><b>Учасники:</b> Редактор, Система
        <font color=000 size=16><b>Передумови:</b> Відсутні
        <font color=000 size=16><b>Результат:</b> Публікація відредагованого звіту
        <font color=000 size=16><b>Виключні ситуації:</b>
        <font color=000 size=16> EX_1.1 Редактор не фахівець даної галузі
        <font color=000 size=16> EX_1.2 Редактор перервав процес редагування
        <font color=000 size=16> EX_1.3 Редактор вніс некоректні зміни
        
        <font color=000 size=16><b>Основний сценарій:</b>
        
    end header

    |Редактор|
        start
        : Натискає кнопку [Редагувати];
    |Система|
        : Перевіряє галузь Редактора;
        note right #ffaaaa
        <b> Можливо
        <b> EX_1.1
        end note

        : Пропонує форму 
           "Редагування";
    |Редактор|    
        : Вносить зміни;
        note right #ffaaaa
        <b> Можливо
        <b> EX_1.2
        end note
        
        : Відправляє зміни;
    |Система|
        : Перевіряє введені дані;
        note right #ffaaaa
        <b> Можливо
        <b> EX_1.3
        end note

        : Публікує відредагований
                         звіт;

        stop;
@enduml
