@startuml
left header
        
        <font color=000 size=16><b>ID:</b> UC_4.1.1
        <font color=000 size=16><b>Назва:</b> Налагодити неполадку
        <font color=000 size=16><b>Учасники:</b> Розробник, Система
        <font color=000 size=16><b>Передумови:</b> Система повертає помилку
        <font color=000 size=16><b>Результат:</b> Неполадки усунені
        <font color=000 size=16><b>Виключні ситуації:</b> Відсутні
        
        <font color=000 size=16><b>Основний сценарій:</b>
        
    end header

    |Розробник|
        start
        : Перевіряє сирцеві коди системи;
        : Виявляє неполадку;
        : Відлагоджує програму;
    |Система|
        : Продовжує коректно функціонувати;
    |Розробник|
        stop;
@enduml
