@startuml
left header
        
        <font color=000 size=16><b>ID:</b> UC_4.2
        <font color=000 size=16><b>Назва:</b> Оновити систему
        <font color=000 size=16><b>Учасники:</b> Розробник, Система
        <font color=000 size=16><b>Передумови:</b> Виправлення помилок
        <font color=000 size=16><b>Результат:</b> Оновлена система
        <font color=000 size=16><b>Виключні ситуації:</b> Відсутні
        
        <font color=000 size=16><b>Основний сценарій:</b>
        
    end header

    |Розробник|
        start
        : Збирає зміни;
        :       Вносить їх у
       сирцевий код порталу;
    |Система|
        : Оновлюється;
    |Розробник|
        stop;
@enduml
