@startuml
left header
        
        <font color=000 size=16><b>ID:</b> UC_4.2
        <font color=000 size=16><b>Назва:</b> Видалити звіт
        <font color=000 size=16><b>Учасники:</b> Автор, Система
        <font color=000 size=16><b>Передумови:</b> Відсутні
        <font color=000 size=16><b>Результат:</b> Видалення звіту
        <font color=000 size=16><b>Виключні ситуації:</b> 
        <font color=000 size=16> EX_4.2.1 Автор відмінив видалення звіту
        
        
        <font color=000 size=16><b>Основний сценарій:</b>
        
    end header

    |Автор|
        start
        : Натиснути кнопку
        "Видалити";
    |Система|
        : Пропронує «Продовжити» для підтвердження;
        note right #ffaaaa
        <b> Можливо
        <b> EX_4.2.1
        end note
    |Автор|
        : Натискає кнопку «Продовжити»;
    |Система|
        : Здійснює реалізацію видалення звіту;
        stop;
@enduml
