@startuml
left header
        
        <font color=000 size=16><b>ID:</b> UC_4.1.2
        <font color=000 size=16><b>Назва:</b> Вести документацію
        <font color=000 size=16><b>Учасники:</b> Розробник, Система
        <font color=000 size=16><b>Передумови:</b> Відсутні
        <font color=000 size=16><b>Результат:</b> Оновлення документації
        <font color=000 size=16><b>Виключні ситуації:</b> Відсутні
        
        <font color=000 size=16><b>Основний сценарій:</b>
        
    end header

    |Розробник|
        start
        : Проводить аналіз
            функціоналу;

        : Розбиває по пунктам
            фунцкії порталу;

        :        Записує у доступному
    для пересічного користувача виді;
    |Система|
        :Оновлює онлайн-документацію;
    |Розробник|
        stop;
@enduml
