@startuml
left header
        
        <font color=000 size=16><b>ID:</b> UC_5.2.1
        <font color=000 size=16><b>Назва:</b> Додати тему
        <font color=000 size=16><b>Учасники:</b> Адміністратор, Система
        <font color=000 size=16><b>Передумови:</b> Тема відсутня в Каталозі
        <font color=000 size=16><b>Результат:</b> Додання теми в Каталог
        <font color=000 size=16><b>Виключні ситуації:</b> Відсутні
        
        <font color=000 size=16><b>Основний сценарій:</b>
        
    end header

    |Користувач|
        start
        : Натискає на кнопку [Додати тему];
    |Система|
        : Виводить форму "Назва та ключові слова";
    |Користувач|
        : Заповнює форму;
    |Система|
        : Додає тему в Каталог;
    stop;
@enduml
