@startuml
left header
        
        <font color=000 size=16><b>ID:</b> UC_5.2.2
        <font color=000 size=16><b>Назва:</b> Видалити тему
        <font color=000 size=16><b>Учасники:</b> Адміністратор, Система
        <font color=000 size=16><b>Передумови:</b> Тема існує
        <font color=000 size=16><b>Результат:</b> Видалення теми з Каталогу
        <font color=000 size=16><b>Виключні ситуації:</b>
        <font color=000 size=16> Відсутні
        
        <font color=000 size=16><b>Основний сценарій:</b>
        
    end header

    |Користувач|
        start
        : Натискає на кнопку [Видалити тему];
    |Система|
        : Виводить форму "Назва та підтвердження";
    |Користувач|
        : Заповнює форму;
    |Система|
        : Видаляє теми з Каталогу;
    stop;
@enduml
