@startuml
left header
        
        <font color=000 size=16><b>ID:</b> UC_5.1.1.2.1
        <font color=000 size=16><b>Назва:</b> Редагувати права користувача
        <font color=000 size=16><b>Учасники:</b> Адміністратор, Система
        <font color=000 size=16><b>Передумови:</b> Відсутні
        <font color=000 size=16><b>Результат:</b> Зміна прав користувача
        <font color=000 size=16><b>Виключні ситуації:</b>
        <font color=000 size=16> EX_5.1 Адміністратор перервав зміну прав
        
        <font color=000 size=16><b>Основний сценарій:</b>
        
    end header

    |Адміністратор|
        start
        : Натискає на кнопку
         [Редагувати права];
    |Система|
        : Відображає список доступних прав;
    |Адміністратор|    
        : Обирає потрібні права;
        note left #ffaaaa
        <b> Можливо
        <b> EX_5.1
        end note

        : Натискає кнопку
             [Зберегети];
        note left #ffaaaa
        <b> Можливо
        <b> EX_5.1
        end note
    |Система|
        : Оновлює права користувача;
    
        stop;
@enduml
