@startuml
    left header
        
        <font color=000 size=16><b>ID:</b> UC_5.1.1
        <font color=000 size=16><b>Назва:</b> Переглянути список користувачів
        <font color=000 size=16><b>Учасники:</b> Адміністратор, Система
        <font color=000 size=16><b>Передумови:</b> Відсутні
        <font color=000 size=16><b>Результат:</b> Відображення списку користувачів
        <font color=000 size=16><b>Виключні ситуації:</b> Відсутні
        
        <font color=000 size=16><b>Основний сценарій:</b>
        
    end header

    |Адміністратор|
        start
        :    Натискає кнопку 
        [Список користувачів];
    |Система|
        : Проводить аналіз БД;

        : Відправляє список;
    |Адміністратор|    
        : Отримує список;
    
        stop;
@enduml
