@startuml
left header
        
        <font color=000 size=16><b>ID:</b> UC_5.1.1.1
        <font color=000 size=16><b>Назва:</b> Застосувати фільтр
        <font color=000 size=16><b>Учасники:</b> Адміністратор, Система
        <font color=000 size=16><b>Передумови:</b> Відсутні
        <font color=000 size=16><b>Результат:</b> Фільтрація користувачів
        <font color=000 size=16><b>Виключні ситуації:</b> Відсутні
        
        <font color=000 size=16><b>Основний сценарій:</b>
        
    end header

    |Адміністратор|
        start
        : Натискає на один з елементів
                           фільтру;
    |Система|
        : Сортує список по обраному фільтру;
    |Адміністратор|    
        : Отримує відсортований список;
    
        stop;
@enduml
