@startuml
package UCD_2.2 {
        usecase "<b>UC_2.2</b>\nПрацювати з наборами\nданих" as UC_2.2 #aaeeaa
    }

    actor "Користувач" as User #eeee99
    
    usecase "<b>UC_2.2.1</b> \nПереглянути список\nзвітів" as UC_2.2.1
    usecase "<b>UC_2.2.2</b> \nЗнайти звіт\n" as UC_2.2.2


    User -l-> UC_2.2
    
    UC_2.2.1 .u.> UC_2.2: extends
    UC_2.2.2 .u.> UC_2.2: extends
@enduml
