@startuml
package UCD_1.0 {
        usecase "<b>UC_1.4</b>\nПрацювати з наборами\nданих" as UC_1.4 #aaeeaa
    }

    actor "Користувач" as Author #eeee99
    
    usecase "<b>UC_1.4.1</b> \nПереглянути набір даних" as UC_1.4.1
    usecase "<b>UC_1.4.2</b> \nЗавантажити набір даних" as UC_1.4.2


    Author -r-> UC_1.4
    
    UC_1.4.1 .u.> UC_1.4: extends
    UC_1.4.2 .u.> UC_1.4: extends
@enduml
