@startuml
package UCD_4.0 {
        usecase "<b>UC_4.1</b>\nПідтримувати\nроботу порталу" as UC_4_1 #aaeeaa
    }

    actor "Розробник" as Developer #eeee99
    
    usecase "<b>UC_4.1.1</b> \nНалагодження" as UC_4_1_1
    usecase "<b>UC_4.1.2</b> \nВести документацію" as UC_4_1_2
    usecase "<b>UC_4.1.3</b> \nУправляти розсилкою" as UC_4_1_3



    Developer -r-> UC_4_1
    
    UC_4_1_1 .u.> UC_4_1: extends
    UC_4_1_2 .u.> UC_4_1: extends
    UC_4_1_3 .u.> UC_4_1: extends
@enduml
